FROM node:22-alpine

WORKDIR /usr/share/www

RUN apk add --no-cache bash bind-tools curl jq \
    && npm install -g openapi-to-postmanv2@5.5.0 newman@6.2.1

COPY api/openbanking.json ./api/openbanking.json
COPY traffic-generator/entrypoint.sh ./entrypoint.sh

RUN chmod 0755 ./entrypoint.sh \
    && chown -R node:node /usr/share/www

USER node
ENTRYPOINT ["/bin/bash", "/usr/share/www/entrypoint.sh"]
