FROM node:22-alpine

WORKDIR /usr/share/www
RUN npm install --omit=dev open-api-mocker@1.7.2

COPY api/openbanking.json ./api/openbanking.json
COPY filter-spec.js ./filter-spec.js
RUN API_PATH_PREFIX=/accounts node ./filter-spec.js

EXPOSE 8080
ENTRYPOINT ["./node_modules/.bin/open-api-mocker"]
CMD ["-s", "./api/service.json", "-p", "8080"]
